---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments

### content configuration ###
title:       "PSES 2019 @ Choisy-le-Roy"
keywords:    "PSES, jekyll, White Rabbit, White Rabbit - PSES, Choisy-le-Roi, activism, hacktivism, privacy, ..."
description: "PSES 2019 est un festival de sensibilisation aux enjeux du numérique et de son développement, mettant en avant des problématique comme le respect de la vie privée"
source_link: "https://github.com/spiderweak/pses-programme-2019-test/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  intro:     '#000000'
  activities:  '#111111'
  program:     '#222222'
  villageasso: '#333333'
  acces:       '#444444'
  manger:      '#555555'
  conduite:    '#666666'
  asso:        '#555555'
  contact:     '#666666'
  mentions:    '#555555'

kramdown:
  auto_ids:  false

sass:
  sass_dir: stylesheets/_sass/
